### ISSUE TITLE
Link's Pocket included as a goal path in multiworld

### ISSUE THREAD

**Issue by mracsys** [TestRunnerSRL/OoT-Randomizer#1733]
This should be impossible as no items are required for the reward in Link's Pocket. Spoiler log is attached.

[OoT_255C5_ZW34F4627R_W3_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/9737712/OoT_255C5_ZW34F4627R_W3_Spoiler.txt)

**Comment by mracsys** [comment]
The seed used a custom hint distribution, see attached.

[s5.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/9737784/s5.txt)

**Comment by fenhl** [comment]
This also happened in this seed with the `mw3` hint distribution: <https://ootrandomizer.com/seed/get?id=1230769>

**Comment by aofengen** [comment]
another instance occurring with https://ootrandomizer.com/seed/get?id=1242156 - I have the spoiler log if people want to look into it, but will not post publicly due to it being a race seed

**Comment by cjohnson57** [comment]
This was fixed by #2021

**Comment by fenhl** [comment]
This is still happening in Dev 7.1.181. For example, [this seed](https://ootrandomizer.com/seed/get?id=1471614) has W1 Deku hinted as path to P3's pocket in the GC maze.

**Comment by fenhl** [comment]
cc @MajikVroom

**Comment by MajikVroom** [comment]
Ah, my group would never see this because we've been playing with #1978 (big fan of that btw), and that causes one_hint_per_goal to be False. Was wondering if we were just getting lucky, since we've been doing a lot of multiworld with path hints.

Anyway, submitted a PR fixing it.
